name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "### Hello world!
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
