name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: get-commit-hash
        run: echo "${GITHUB_SHA}"
      - name: get-committed-file
        run: |
          echo "The contents of the committed file are:"
          cat "$(git show $GITHUB_SHA | grep -Eo '^diff --git a/.* b/.*')"



