name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Print Hello, World!'
        run: node hello.js
      - name: Fetch Commit Author
        run: |

          commit_author=$(git log -1 --pretty=format:'%an')

          echo "Commit Author: $commit_author"
      - name: Echo Author in GitHub Actions
        run: |

          echo "Commit Author: ${{ github.actor }}"
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        run: python main.py
